to_do_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'todos#index'
  
  resources :todos  
  resources :lists 
  
end

to_do_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

to_do_app/app/models/list.rb
class List < ApplicationRecord
   belongs_to :todo 
end

to_do_app/app/models/todo.rb
class Todo < ApplicationRecord
    has_many :lists
end

to_do_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

to_do_app/app/controllers/lists_controller.rb
class ListsController < ApplicationController
    
    def index
        @todo = Todo.find(params[:todo_id])
        @lists = @todo.lists
    end
    
    def show
        @list = List.find(params[:id])
    end
    
    def new
        @list = List.new
    end
    
    def create
        @list = List.new(list_params)
        if @list.valid?
            @author.save
            redirect_to @list
        else
            flash[:list] = @list.errors.messages
            redirect_back fallback_location: new_list_path
        end
    end
    
    def edit 
        @list = List.find(params[:id])
    end
    
    def update
        @list = List.find(params[:id])
        if @list.update(list_params)
            redirect_to @list
        else
            redirect_back fallback_location: edit_list_path(@list)
        end
    end
    
    def destroy
        @list = List.find(params[:id])
        puts @list
        if @list.destroy
            redirect_to todos_path
        else
            redirect_back fallback_location: @list
        end
    end

    private
    
    def list_params
        params.require(:list).permit(:title, :description)
    end
    
    def set_list
        @list = List.find(params[:id])
    end
end

to_do_app/app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
        @todos = Todo.all 
    end
    
    def show 
        @todo = Todo.find(params[:id])
        @lists = @todo.lists
    end
    
end

to_do_app/app/helpers/application_helper.rb
module ApplicationHelper
end

to_do_app/app/helpers/lists_helper.rb
module ListsHelper
end

to_do_app/app/helpers/todos_helper.rb
module TodosHelper
end

to_do_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>

to_do_app/app/views/lists/edit.html.erb
<h1 class="edit-item">Edit List</h1>
<%= render "partials/list_form", {list: @list} %>

to_do_app/app/views/lists/index.html.erb
<h1><%= "#{@todo.title}'s to-do items" %></h1>

<div class="index-page">
    <% @lists.each do |list| %>
        <br>
        <%= link_to list.title, todo_list_path(@todo, list) %>
    <% end %>
</div>

to_do_app/app/views/lists/new.html.erb
<h1 class="new-list">New List Item</h1>
<%= render "partials/list_form", {list: @list} %>

to_do_app/app/views/lists/show.html.erb
<div class="show">
    <h1><%= @list.title%></h1>
    <h2><%= @list.description %></h2>
    <div class="edit-button">
        <%= link_to("edit", edit_list_path(@list), :class => "open-button") %>
        <%= link_to("delete", @list, method: :delete, :class=>"open-button") %>
    </div>
</div>

to_do_app/app/views/partials/_list_form.html.erb
<%= form_for(list, :html => {:class => "form"}) do |f| %>
  <div class="input">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="input">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <%= f.submit %>
<% end %>

to_do_app/app/views/todos/index.html.erb
<h1>My To Do List For The Day</h1>

<div class="to-do-list">
    <% @todos.each do |todo| %>
    <p><%= link_to todo.title, todo_path(todo) %></p>
    <% end %>
</div>

to_do_app/app/views/todos/show.html.erb
<h1><%= @todo.title %></h1>
<h2>Hello</h2>
<ul>
    <% @lists.each do |list|%>
    <li><%= link_to list.title, list_path(list[:id]) %></li>
    <% end %>
</ul>


<%= link_to "Back to list", todos_path %>